name: markrhickey
favicon: null
layout_spectrum: 0.2456
typography_spectrum: 0.58949
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9C958D'
    - '#212121'
    - '#BDC0C9'
    - '#465C83'
    - '#423D39'
  brandStrength: 1
  lightness: 0.65069101145491
  saturation: 0.8211014473345131
  rhythmicContrast: 0.444294617511332
purpose: []
